language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "node"

git:
  depth: 3

branches:
  only:
    - master

notifications:
  email:
    - travis@treeline.io

# Provide Travis with access to a Redis server
before_script: sudo redis-server /etc/redis/redis.conf
